[package]
name = "just"
version = "0.1.0"
description = "A handy way to save and run project-specific commands"
homepage = "https://github.com/casey/just"
license = "CC0-1.0"
url = "https://github.com/vicvenscob/just/archive/refs/heads/master.tar.gz"
depends = []
post_install = "cargo build --release && cp target/release/just /usr/local/bin/just"

[package.files]
